# -*- coding: utf-8 -*-
"""Criptografía Clasica y Moderna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQ3wkQ5DC5CbYdqdHNC78gvgX5ihdjaJ

a. Cifrado César
1. Crea funciones para cifrar y descifrar texto usando el cifrado César (clave variable).
2. Prueba con tu nombre y una frase.
3. Implementa ataque de fuerza bruta: muestra todas las combinaciones posibles para
un mensaje cifrado (sin clave).
4. Explica brevemente en el video cómo funciona el cifrado y el ataque.
b. Cifrado Vigenère
1. Programa funciones de cifrado y descifrado con clave alfabética.
2. Prueba con un mensaje propio.
3. Explica cómo el Vigenère dificulta el análisis de frecuencia en el video.
c. Cifrado simétrico moderno (Fernet/AES)
1. Usa la librería cryptography para cifrar/descifrar un mensaje o archivo.
2. Explica por qué es más seguro que los cifrados clásicos y discute modos de
operación (ECB/CBC) en el video.
"""

# === COMPLETA LOS DATOS DEL GRUPO ===

# Integrante 1
nombre_1 = "Yoann Esteban Jacome Garcia"
codigo_1 = "1202597"

# Integrante 2
nombre_2 = "David Santiago Crispoca Taborda"
codigo_2 = "1202557"

# Integrante 3 (si aplica)
nombre_3 = "María Alejandra Suarez Cuesta"
codigo_3 = "1202604"

integrantes = [(nombre_1, codigo_1), (nombre_2, codigo_2)]
if nombre_3:
    integrantes.append((nombre_3, codigo_3))

print("Grupo de trabajo:")
for i, (n, c) in enumerate(integrantes, 1):
    print(f"  {i}. {n} — {c}")

"""a. Cifrado César"""

# Ejecuta esta celda para instalar las dependencias
!pip install pycryptodome Pillow -q
print("✅ Librerías instaladas correctamente.")

# Re utilización del codigo brindado por el docente en la sesion 3
# Creación funcion de cifrado cesar, con los siguientes parametros:
# Texto: Mensaje original a cifrar
# Desplazamiento: Entero con cantidad de corrimientos en el abecedario
def cifrado_cesar(texto, desplazamiento):
    resultado = ""
    # Se implementa un for para iterar en el abecedario la cantidad de veces requeridas para cifrar el mensaje
    for caracter in texto:
        if caracter.isalpha(): # se verifica que el mensaje este con valores alpha numericos
            base = ord('A') if caracter.isupper() else ord('a')
            nuevo = (ord(caracter) - base + desplazamiento) % 26 # Se desplaza los caracteres del mensaje segun el valor de desplazamiento
            resultado += chr(base + nuevo)
        else:
            resultado += caracter
    return resultado

# Ejemplo de uso
mensaje = "Soy Yoann Jacome, estudio Ingeneria en Multimedia"
cifrado = cifrado_cesar(mensaje, 5)
print(f"Mensaje original: {mensaje}")
print(f"Cifrado (desplazamiento 5): {cifrado}")

# Creacion de variable donde se descifra el mensaje, para esta se hace uso de la misma funcion de cifrado cesar pero el desplazamiento sera el mismo valor
# pero en negativo, para que el corrimiento se haga hacia atras
descifrado = cifrado_cesar(cifrado, -5)
print(f"Descifrado: {descifrado}") # Se imprime el mensaje cifrado

# Re utilización del codigo brindado por el docente en la sesion 3
# Prueba de fuerza bruta para descifrar el mensaje, obteniendo todas las 26 combinaciones posibles
mensaje_secreto = cifrado_cesar("Alejandra", 21) # Se manda el mensaje "Alejandra" con un entero de 21 casillas a mover
print(f"Mensaje cifrado a romper: {mensaje_secreto}\n") # Se imprime el resultado del mensaje cifrado

print("Ataque de fuerza bruta:")
for i in range(26): # ciclo for para imprimir las 26 distintas posibilidades de desplazamiento
    intento = cifrado_cesar(mensaje_secreto, -i)
    print(f"  Desplazamiento {i:2d}: {intento}") # Se imprime el intento actual segun el valor de la variable ciclica "i"

"""B. cifrado vigenére"""

# Re utilización del codigo brindado por el docente en la sesion 3
# Creación funcion de cifrado vigenere
def cifrado_vigenere(texto, clave, modo='cifrar'):
    resultado = ""
    clave = clave.upper()
    j = 0  # índice para recorrer la clave

    for caracter in texto: # Ciclo for para iterar la cantidad de veces necesaria la clave para completar el mensaje
        if caracter.isalpha():
            base = ord('A') if caracter.isupper() else ord('a')
            desplazamiento = ord(clave[j % len(clave)]) - ord('A')

            if modo == 'descifrar': # Se define el modo de descrifrar con la funcionalidad de devolver la cantidad de casillas desplazadas en el corrimiento
                desplazamiento = -desplazamiento

            nuevo = (ord(caracter) - base + desplazamiento) % 26
            resultado += chr(base + nuevo)
            j += 1
        else:
            resultado += caracter

    return resultado

# Cifrar
mensaje = "Este es cifrado vigenere" # Variable que almacena el mensaje
clave = "SEGURIDAD" # Variable que almacena la clave
cifrado = cifrado_vigenere(mensaje, clave, 'cifrar') #Llamado a la funcion de cifrado con el mensaje, clave y modo 'cifrar'
print(f"Mensaje original: {mensaje}")
print(f"Clave: {clave}")
print(f"Cifrado: {cifrado}") #Se imprime el mensaje cifrado

# Creacion funcion de descifrado Vigenere.
descifrado = cifrado_vigenere(cifrado, clave, 'descifrar') #Llamado a la funcion de cifrado con el mensaje, clave y modo 'descifrar'
print(f"Descifrado: {descifrado}") #Se imprime el mensaje descifrado

"""c. Cifrado simétrico moderno (Fernet/AES)"""

# Re utilización del codigo brindado por el docente en la sesion 3
#Importacion libreria cryptography
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad
from Crypto.Random import get_random_bytes
import binascii

# Generar una llave de 16 bytes (128 bits)
llave = get_random_bytes(16)
mensaje = "Este es un mensaje de prueba AES."
mensaje_bytes = mensaje.encode('utf-8')

# MODO ECB
cifrador_ecb = AES.new(llave, AES.MODE_ECB) # Se crea una variable cifradora que contiene la llave y el modo
cifrado_ecb = cifrador_ecb.encrypt(pad(mensaje_bytes, 16)) # Cifra el mensaje y lo rellena para que su longitud sea múltiplo de 16 bytes antes de cifrar
print("MODO ECB: ")
print(f"Cifrado (hex): {binascii.hexlify(cifrado_ecb).decode()}") # Se imprime el resultado en hexadecimal

# Descifrar ECB
descifrador_ecb = AES.new(llave, AES.MODE_ECB) # Se crea la variable descifradora haciendo uso de la llave y el mismo modo
descifrado_ecb = unpad(descifrador_ecb.decrypt(cifrado_ecb), 16) # Quita el relleno que se agregó antes de cifrar, para recuperar el mensaje original exacto.
print(f"Descifrado: {descifrado_ecb.decode()}") # Se imprime el resultado del mensaje descifrado

# MODO CBC
iv = get_random_bytes(16)  # Vector de inicialización
# Se cifra el mensaje con la llave y haciendo uso del vector de inicializacion para combinar con el primer bloque y romper la similitud en caso de tener el mismo valor,
# Luego cada bloque cifrado se combina con el bloque anterior antes de cifrar el siguiente
cifrador_cbc = AES.new(llave, AES.MODE_CBC, iv=iv)
cifrado_cbc = cifrador_cbc.encrypt(pad(mensaje_bytes, 16)) #Cifra el mensaje y lo rellena para que su longitud sea múltiplo de 16 bytes antes de cifrar
print("MODO CBC: ")
print(f"Cifrado (hex): {binascii.hexlify(cifrado_cbc).decode()}")

# Descifrar CBC
# Para descifrar el mensaje se hace uso del mismo iv, para poder descrifrar correctamente
descifrador_cbc = AES.new(llave, AES.MODE_CBC, iv=iv)
descifrado_cbc = unpad(descifrador_cbc.decrypt(cifrado_cbc), 16) # Quita el relleno que se agregó antes de cifrar, para recuperar el mensaje original exacto.
print(f"Descifrado: {descifrado_cbc.decode()}") # Se imprime el resultado del mensaje descifrado