# -*- coding: utf-8 -*-
"""EjercicioTecnicoHTTPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tRwxXM2yKLTf473P1BvgDgpwwYkofnYo

HTTPS (ejercicio técnico)
1. Utiliza Python (librería requests) para hacer una petición a un sitio web que
tenga HTTPS y otro sin HTTPS.
2. Revisa la diferencia, los encabezados y errores posibles.
3. Verifica cómo se comprueba la validez de un certificado SSL/TLS.
"""

# === COMPLETA LOS DATOS DEL GRUPO ===

# Integrante 1
nombre_1 = "Yoann Esteban Jacome Garcia"
codigo_1 = "1202597"

# Integrante 2
nombre_2 = "David Santiago Crispoca Taborda"
codigo_2 = "1202557"

# Integrante 3 (si aplica)
nombre_3 = "María Alejandra Suarez Cuesta"
codigo_3 = "1202604"

integrantes = [(nombre_1, codigo_1), (nombre_2, codigo_2)]
if nombre_3:
    integrantes.append((nombre_3, codigo_3))

print("Grupo de trabajo:")
for i, (n, c) in enumerate(integrantes, 1):
    print(f"  {i}. {n} — {c}")

# Importación de la librería requests para hacer peticiones HTTP/HTTPS
import requests

# Se hace una petición GET a un sitio que usa HTTPS
respuesta_https = requests.get("https://www.python.org")

print("=== Sitio CON HTTPS ===")
print("Código de estado:", respuesta_https.status_code)  # 200 significa que la petición fue exitosa
print("URL final:", respuesta_https.url)
print("¿Usó HTTPS?:", respuesta_https.url.startswith("https"))  # confirma si la URL final empieza con "https"

# Petición a un sitio que ofrece HTTP sin cifrar
print("Sitio SIN HTTPS:  ")
# Se usa try/except por si la conexión falla, en vez de detener todo el programa, ejecuta esta otra parte (except) y sigue adelante normalmente
try:
    # timeout=10 evita que la petición se quede esperando indefinidamente si el sitio no responde
    respuesta_http = requests.get("http://neverssl.com", timeout=10)
    print("Código de estado:", respuesta_http.status_code)
    print("URL final:", respuesta_http.url)
    print("¿Usó HTTPS?:", respuesta_http.url.startswith("https"))
except requests.exceptions.ConnectionError as e:
    print("No se pudo establecer la conexión HTTP (posible bloqueo de red del entorno).")
    print("Tipo de error:", type(e).__name__)  # muestra el nombre de la clase del error capturado

# Se recorren los encabezados de la respuesta HTTPS
print("Encabezados del sitio HTTPS:")
for clave, valor in respuesta_https.headers.items():
    print(f"  {clave}: {valor}")

print()

# Se recorren los encabezados de la respuesta HTTP, para poder comparar contra los de HTTPS
# Solo se hace si la petición HTTP fue exitosa (si falló antes, respuesta_http no existiría)
print("Encabezados del sitio HTTP:")
if 'respuesta_http' in dir():
    for clave, valor in respuesta_http.headers.items():
        print(f"  {clave}: {valor}")
else:
    print("  No se pudo obtener, la conexión HTTP falló anteriormente.")

# Se usa un sitio de pruebas con certificado vencido, hecho a propósito para provocar el error
try:
    requests.get("https://expired.badssl.com", timeout=10)
except requests.exceptions.SSLError as e:
    # Se captura específicamente el error de SSL, que se lanza cuando el certificado no es válido
    print("Error SSL capturado:")
    print(type(e).__name__)

# Importación de librerías: ssl para manejar la validación de certificados, socket para la conexión de red
import ssl
import socket

# Función para obtener la información del certificado de un sitio, tomando como parámetros el host (dominio) y el puerto (443 por defecto, el estándar de HTTPS)
def obtener_info_certificado(host, puerto=443):
    contexto = ssl.create_default_context()  # crea un contexto que valida el certificado con las reglas estándar (vencimiento, dominio, autoridad certificadora)

    # Se abre una conexión de red normal hacia el host y puerto indicados
    with socket.create_connection((host, puerto), timeout=10) as sock:
        # Se "envuelve" esa conexión con TLS, indicando el nombre del host para que se valide correctamente
        with contexto.wrap_socket(sock, server_hostname=host) as ssock:
            cert = ssock.getpeercert()  # obtiene los datos del certificado que presentó el servidor
            return cert

# Se llama a la función pasando el dominio a inspeccionar, y se guarda el resultado en "info"
info = obtener_info_certificado("www.python.org")

print("Emitido para:", info.get("subject"))                      # a quién pertenece el certificado
print("Emitido por (autoridad certificadora):", info.get("issuer"))  # quién lo emitió (la CA)
print("Válido desde:", info.get("notBefore"))                    # fecha de inicio de validez
print("Válido hasta:", info.get("notAfter"))                     # fecha de vencimiento