# -*- coding: utf-8 -*-
"""Funciones Hash y HMAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pO62rvIzlsKhnUXn0EwbvgsxsyzrTehi

Funciones Hash y HMAC (50/500)
a. SHA-256
1. Aplica hashlib para obtener el hash de textos y archivos, muestra cómo cambia si el
contenido se modifica.
2. Explica en el video la importancia de la irreversibilidad y resistencia a colisiones.
b. Detección de integridad
1. Crea función para comparar hashes de dos archivos y verificar si son idénticos.
2. Muestra y explica un ejemplo en el video.
c. HMAC
1. Investiga y programa la generación y verificación de HMAC con SHA-256 y clave.
2. Comenta en el video cuándo usar HMAC y diferencias con hash simple.

a. SHA-256
"""

# Re utilización del codigo brindado por el docente en la sesion 3
# Importacion de libreria hashlib
import hashlib

# Creación de función para calcular el hash: tomando como parametro el texto
def calcular_hash(texto):
    return hashlib.sha256(texto.encode('utf-8')).hexdigest() # Usando la libreria hashlib se usa la funcion de calculo de hash

# Ejemplo: Hash de mensajes similares
mensaje1 = "Prueba Hash"
mensaje2 = "Prueba hash"   # Solo cambia la H por h
mensaje3 = "Prueba Hash"   # Igual al mensaje 1

# Se calcula el hash de cada mensaje
hash1 = calcular_hash(mensaje1)
hash2 = calcular_hash(mensaje2)
hash3 = calcular_hash(mensaje3)

# Se imprime cada mensaje con su correspondiente hash
print(f"Mensaje 1: \"{mensaje1}\"  →  Hash: {hash1}")
print(f"Mensaje 2: \"{mensaje2}\"  →  Hash: {hash2}")
print(f"Mensaje 3: \"{mensaje3}\"  →  Hash: {hash3}")

"""b. Detección de integridad"""

# Re utilización del codigo brindado por el docente en la sesion 3
# Importación libreria haslib para usar algoritmos de sha-256
import hashlib

# Funcion para calcular el hash SHA-256 de un archivo, tomando como parametro el nombre del archivo
def hash_archivo(nombre_archivo):
  # Se crea primero un objeto hash vacío, ideal para archivos grandes: no hace falta cargar todo el archivo en memoria de una vez.
    sha256 = hashlib.sha256()
    with open(nombre_archivo, 'rb') as f: #abre el archivo en modo 'rb' (read binary)
        while True: #Ciclo while para leer el contenido interno del archivo por partes
            bloque = f.read(4096) # Lee el siguiente pedazo del archivo, de máximo 4096 bytes (4 KB).
            if not bloque: # Si se detecta falta de contenido en la lectura se detiene el bucle
                break
            sha256.update(bloque)
    return sha256.hexdigest() # Retorna el resultado final del hash

# Prueba de calculo del hash
# Paso 1: Crear un archivo de prueba
with open('pruebahash.txt', 'w') as f:
    f.write('Este es un texto de prueba.')

# Paso 2: Calcular hash original
hash_original = hash_archivo('pruebahash.txt') # Se llama la función de calculo del hash dandole como parametro el nombre del archivo
print(f"Hash original:   {hash_original}") # Se imprime el hash obtenido

# Paso 3: Simular una modificación (se altera el contenido del archivo)
with open('pruebahash.txt', 'a') as f:
    f.write(' Modificacion de archivo.') # Se incluye dentro del archivo un mensaje

# Paso 4: Calcular hash después de la modificación
hash_modificado = hash_archivo('pruebahash.txt')
print(f"Hash modificado: {hash_modificado}")

# Paso 5: Verificar integridad
if hash_original == hash_modificado: #Se compara el hash original con el hash obtenido tras modificar el archivo
    print("\n✅ El archivo NO ha sido modificado.")
else:
    print("\n🚨 ALERTA: ¡El archivo fue modificado!")

"""c. HMAC"""

# Se importa la libreria hmac y hashlib
import hmac
import hashlib

def generar_hmac(mensaje: str, clave: str) -> str: # La flecha, indica el tipo de dato que va a devolver, en este caso un string, que será el código HMAC final en formato hexadecimal
    # Genera el código HMAC-SHA256 en formato hexadecimal
    # Convertir el mensaje y la clave a bytes
    clave_bytes = clave.encode('utf-8')
    mensaje_bytes = mensaje.encode('utf-8')

    # Crear el objeto HMAC con la clave, el mensaje y el algoritmo SHA-256
    objeto_hmac = hmac.new(clave_bytes, mensaje_bytes, hashlib.sha256)

    # Retornar la firma en formato hexadecimal
    return objeto_hmac.hexdigest()

def verificar_hmac(mensaje: str, clave: str, firma_recibida: str) -> bool: # La flecha -> indica qué tipo de dato va a devolver un bool, que será la verificacion de si la firma recibida coincide con el mensaje y la clave
    # Verifica si la firma recibida coincide con el mensaje y la clave
    # Generar una nueva firma local usando los mismos datos
    firma_esperada = generar_hmac(mensaje, clave)

    return firma_esperada == firma_recibida

# EJEMPLO
# Creacion variables con clave secreta y mensaje
mi_clave_secreta = "Clave123"
mi_mensaje = "Este es un mensaje seguro."

print(f"Mensaje original: {mi_mensaje}")
print(f"Clave secreta:    {mi_clave_secreta}\n")

# Creacion de variable que almacena la firma obtenida en la funcion generar_hmac
firma = generar_hmac(mi_mensaje, mi_clave_secreta)
print(f"HMAC Generado (SHA-256): {firma}\n")

# Verificacion de validez del hmac, segun el mensaje, clave secreta y firma obtenida
es_valido = verificar_hmac(mi_mensaje, mi_clave_secreta, firma)
print(f"¿La firma es válida?: {es_valido}") # Debería ser True

# Se crea un mensaje alterado para verificar si es valido
mensaje_alterado = "Este es un mensaje seguro!"
# Al modificar el contenido se debe obtener una firma distinta por lo tanto al diferenciarlos deberia indicarse
es_valido_alterado = verificar_hmac(mensaje_alterado, mi_clave_secreta, firma)
print(f"¿El mensaje alterado es válido?: {es_valido_alterado}") # Debería ser False