# -*- coding: utf-8 -*-
"""Introducción Práctica a Blockchain (simulación básica).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eOsrB4-AFEKnWIaiU4h6SC8r2hlQ_iM_

Objetivo: Visualizar el funcionamiento de una cadena de bloques y el concepto de
inmutabilidad.
Pasos:
1. Implementa una estructura simple de bloque en Python (con campos de datos,
timestamp, hash del bloque anterior y propio).
2. Crea una “cadena” añadiendo varios bloques con información ficticia.
3. Verifica cómo se calcula el hash y cómo se encadena la información.
4. Modifica la información de un bloque y observa cómo los hashes cambian y se
“rompe” la cadena.
Desafío adicional:
Agrega validación de integridad de la cadena (función que revise automáticamente si
la cadena es válida).
Reflexión:
¿Por qué la inmutabilidad y el consenso son claves en la seguridad de blockchain?
"""

# === COMPLETA LOS DATOS DEL GRUPO ===

# Integrante 1
nombre_1 = "Yoann Esteban Jacome Garcia"
codigo_1 = "1202597"

# Integrante 2
nombre_2 = "David Santiago Crispoca Taborda"
codigo_2 = "1202557"

# Integrante 3 (si aplica)
nombre_3 = "María Alejandra Suarez Cuesta"
codigo_3 = "1202604"

integrantes = [(nombre_1, codigo_1), (nombre_2, codigo_2)]
if nombre_3:
    integrantes.append((nombre_3, codigo_3))

print("Grupo de trabajo:")
for i, (n, c) in enumerate(integrantes, 1):
    print(f"  {i}. {n} — {c}")

# Importación de librerías: hashlib para calcular los hashes SHA-256, datetime para el timestamp de cada bloque
import hashlib
import datetime

# Se define la clase de bloque, donde se almacena los siguientes datos:
# Indice: Posicion del bloque en la cadena
# Timestamp: Fecha u hora exacta de cuando se creo el bloque
# Datos: la información real que se busca guardar, puede ser un mensajes, textos, registros etc
# Hash_anterior: El hash del bloque anterior, necesario para crear la cadena, en caso de ser el primer bloque se tiene un valor de "0"
# Hash_propio: Se calcula el hash del bloque actual con la funcion "calcular_hash", para posteriormente ser recibido por el siguiente bloque de la cadena

class Bloque:
    def __init__(self, indice, datos, hash_anterior):
       # El constructor recibe el índice, los datos a guardar, y el hash del bloque anterior
        self.indice = indice
        self.timestamp = str(datetime.datetime.now())
        self.datos = datos
        self.hash_anterior = hash_anterior
        self.hash_propio = self.calcular_hash() # Para calcular el hash propio se realiza dentro del mismo __init__ llamando luego a la funcion calcular_hash

   # Función para calcular el hash del bloque, no recibe parámetros porque usa los datos propios del bloque (self)
    def calcular_hash(self):
       # Se juntan todos los datos del bloque en un solo texto antes de aplicar el hash
        contenido = f"{self.indice}{self.timestamp}{self.datos}{self.hash_anterior}"
        return hashlib.sha256(contenido.encode('utf-8')).hexdigest()

   # Define como se muestra el bloque al imprimirlo, para poder revisarlo fácilmente en pantalla
    def __repr__(self):
        return (f"Bloque #{self.indice}\n"
                f"  Datos: {self.datos}\n"
                f"  Hash anterior: {self.hash_anterior}\n"
                f"  Hash propio:   {self.hash_propio}")

# Esta clase administra la lista de bloques y las reglas de la cadena
class Blockchain:
   # Al crear la blockchain, se inicia automáticamente con el bloque génesis dentro de la lista
    def __init__(self):
        self.cadena = [self.crear_bloque_genesis()]

    #Función de creación de bloque principal
    def crear_bloque_genesis(self):
        # primer bloque, no tiene bloque anterior real
        return Bloque(0, "Bloque genesis", "0")

    #Función de ayuda la cual devuelve el último bloque de la lista . El cual necesitamos porque cada bloque nuevo tiene que saber cuál es el hash del bloque que quedó de último.
    def obtener_ultimo_bloque(self):
        return self.cadena[-1]

    # Función para agregar bloques, tomando como parámetro los datos a guardar en el nuevo bloque
    # Obtiene el bloque anterior y le pasa su hash_propio para definirlo como hash_anterior en el bloque a crear, luego lo agrega a la lista
    def agregar_bloque(self, datos):
        anterior = self.obtener_ultimo_bloque()
        nuevo = Bloque(len(self.cadena), datos, anterior.hash_propio)
        self.cadena.append(nuevo)

     # En esta función se detecta si alguien manipuló la cadena, no recibe parámetros porque revisa toda la cadena propia (self.cadena)
    def es_valida(self):
        # recorre la cadena revisando dos cosas en cada bloque:
        # 1) Que su hash siga correspondiendo a su contenido actual
        # 2) Que su hash_anterior coincida con el hash real del bloque previo
        for i in range(1, len(self.cadena)):
            actual = self.cadena[i]
            anterior = self.cadena[i - 1]

            if actual.hash_propio != actual.calcular_hash():
                return False
            if actual.hash_anterior != anterior.hash_propio:
                return False
        return True

# Creacion de cadena de prueba con dos bloques, aparte del bloque "genesis" (primer bloque)
mi_cadena = Blockchain()
mi_cadena.agregar_bloque("Alice envia 10 a Bob")
mi_cadena.agregar_bloque("Bob envia 5 a Charlie")

# Se recorre e imprime cada bloque de la cadena para revisar su contenido y sus hashes
for b in mi_cadena.cadena:
    print(b)
    print()

# Se valida la cadena completa, en este punto todavía no ha sido alterada
print("Cadena valida:", mi_cadena.es_valida())  # True

# Se guarda el hash_propio original del bloque 1 antes de alterarlo, para poder comparar después
hash_propio_original = mi_cadena.cadena[1].hash_propio

# Se cambia el dato del bloque 1 directamente, sin volver a calcular su hash
mi_cadena.cadena[1].datos = "Alice envia 1000 a Bob"

# Se recalcula el hash del bloque con su contenido ya alterado, solo para comparar (no se guarda en el bloque)
hash_recalculado = mi_cadena.cadena[1].calcular_hash()

print("=" * 60)
print("CADENA DESPUÉS DE ALTERAR EL BLOQUE 1")
print("=" * 60)

# Se recorre e imprime la cadena completa, ya con el bloque alterado
for b in mi_cadena.cadena:
    print(b)
    print()

print("-" * 60)
print("Comparación del bloque alterado (Bloque #1):")
print(f"  Hash guardado (viejo):      {hash_propio_original}")
print(f"  Hash recalculado (nuevo):   {hash_recalculado}")
print(f"  ¿Coinciden?: {hash_propio_original == hash_recalculado}")
print("-" * 60)

# Se vuelve a validar la cadena, ahora debería detectar la alteración
print("Cadena válida después de alterar:", mi_cadena.es_valida())  # False