# -*- coding: utf-8 -*-
"""Autenticación con hash y sal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtOGCRZQ3GeT_Gg27Asvd9cYFfvsXoMB

Autenticación con hash y sal (50/500)
Simula registro/inicio de sesión guardando el hash (usa SHA-256).
Integra el concepto de “sal” para evitar ataques de diccionario.
Explica riesgos y la importancia de la sal en el video.
"""

# === COMPLETA LOS DATOS DEL GRUPO ===

# Integrante 1
nombre_1 = "Yoann Esteban Jacome Garcia"
codigo_1 = "1202597"

# Integrante 2
nombre_2 = "David Santiago Crispoca Taborda"
codigo_2 = "1202557"

# Integrante 3 (si aplica)
nombre_3 = "María Alejandra Suarez Cuesta"
codigo_3 = "1202604"

integrantes = [(nombre_1, codigo_1), (nombre_2, codigo_2)]
if nombre_3:
    integrantes.append((nombre_3, codigo_3))

print("Grupo de trabajo:")
for i, (n, c) in enumerate(integrantes, 1):
    print(f"  {i}. {n} — {c}")

# Importación de librerías: hashlib para el hash SHA-256, os para generar bytes aleatorios (la sal)
import hashlib
import os

# "Base de datos" en memoria: guarda usuario, osea la sal generada y su hash. En un sistema real sería una tabla de base de datos
usuarios_db = {}

# Función para generar una sal aleatoria en formato hexadecimal, tomando como parámetro la longitud en bytes (16 en este caso), esta funcion retornara un string que es la sal generada
# Que es la sal y para que funciona:
# La sal es un valor aleatorio que se combina con la contraseña antes de aplicar el hash, esto sirve para evitar que dos usuarios con la misma contraseña obtengan el mismo hash
def generar_sal(longitud_bytes: int = 16) -> str:
    return os.urandom(longitud_bytes).hex()  # os.urandom genera bytes aleatorios seguros, y .hex() los convierte a texto hexadecimal legible

# Función para calcular el hash de una contraseña combinada con su sal, tomando ambos como parámetros y retornando un string que sera el hash
def hash_contrasena(contrasena: str, sal: str) -> str:
    # Combina la sal con la contraseña y calcula el hash SHA-256
    combinado = (sal + contrasena).encode('utf-8')
    return hashlib.sha256(combinado).hexdigest() # Se retorna el valor obtenido en este caso el hash

# Función que simula el registro de un usuario, tomando como parámetros el nombre de usuario y la contraseña
def registrar_usuario(usuario: str, contrasena: str) -> bool:

    # Condicional para evitar que se registre un usuario ya existente
    if usuario in usuarios_db:
        print(f"El usuario '{usuario}' ya existe.")
        return False

    # Se hace llamado a la funcion de general_sal y se almacena en una variable
    sal = generar_sal()                              #  Sal única para este usuario
    hash_guardado = hash_contrasena(contrasena, sal)  # Hash de (sal + contraseña)

    # Se guarda SOLO sal y hash, pero la contraseña original nunca se almacena
    usuarios_db[usuario] = {"sal": sal, "hash": hash_guardado}

    # Se imprime la informacion del usuario registrado (sal y hash) y si se registro correctamente
    print(f"Usuario '{usuario}' registrado correctamente.")
    print(f"Sal generada:   {sal}")
    print(f"Hash guardado:  {hash_guardado}")
    return True

# Función que simula el inicio de sesión, tomando como parámetros el usuario y la contraseña ingresada, se retorna un valor bool, true para ingreso exitoso, false para lo contrario
def iniciar_sesion(usuario: str, contrasena: str) -> bool:
    # Se valida con un condicional de que el usuario exista en la memoria
    if usuario not in usuarios_db:
        print(" Usuario no encontrado.") # Se notifica en caso de no encontrar el usuario
        return False

    datos = usuarios_db[usuario]
    # Se repite el mismo cálculo del registro, usando la sal ya guardada, no una nueva
    hash_calculado = hash_contrasena(contrasena, datos["sal"])

    # Se imprime la información procesada
    print(f"Sal usada:        {datos['sal']}")
    print(f"Hash calculado:   {hash_calculado}")
    print(f"Hash almacenado:  {datos['hash']}")

    # Se compara el hash recién calculado contra el hash guardado en el registro
    if hash_calculado == datos["hash"]:
        print(f"Login exitoso. Bienvenido, {usuario}.")
        return True
    else:
        print("Contraseña incorrecta.")
        return False

# Prueba rápida de la lógica
# Registro manual de un usuario con usuario: "yoann", clave: "MiClave123"
registrar_usuario("yoann", "MiClave123")
iniciar_sesion("yoann", "MiClave123")   # debería ser True
iniciar_sesion("yoann", "otraClave")    # debería ser False

# Demostración de funcionalidad de la sal:
registrar_usuario("otro_usuario", "MiClave123")  # misma contraseña que usuario "yoann"
print("¿Mismo hash aunque la contraseña sea igual?",
      usuarios_db["yoann"]["hash"] == usuarios_db["otro_usuario"]["hash"])
# Debería imprimir False -> cada usuario tiene un hash distinto gracias a su sal

# Importación de ipywidgets para crear los campos de texto, y display/clear_output para mostrarlos y refrescarlos
import ipywidgets as widgets
from IPython.display import display, clear_output

# Campo de registro grafico
txt_reg_usuario = widgets.Text(description="Usuario:")
txt_reg_clave = widgets.Password(description="Contraseña:")
btn_registrar = widgets.Button(description="Registrarse", button_style="success")
salida_registro = widgets.Output()

# Función que se ejecuta al hacer clic en el botón, tomando como parámetro el botón mismo (b)
def on_registrar_click(b):
    with salida_registro:
        clear_output() # Limpia lo que se haya impreso antes, para no acumular resultados
        registrar_usuario(txt_reg_usuario.value, txt_reg_clave.value) # Llama al registro con lo que el usuario escribió

btn_registrar.on_click(on_registrar_click) # Conecta el botón con la función de arriba

# Se imprime el formulario de registro con sus campos de ingreso
print("=== Formulario de Registro ===")
display(txt_reg_usuario, txt_reg_clave, btn_registrar, salida_registro)

# Campos de login gráfico
txt_login_usuario = widgets.Text(description="Usuario:")
txt_login_clave = widgets.Password(description="Contraseña:")
btn_login = widgets.Button(description="Iniciar sesión", button_style="info")
salida_login = widgets.Output()

# Función que se ejecuta al hacer clic en el botón, tomando como parámetro el botón mismo (b)
def on_login_click(b):
    with salida_login:
        clear_output() # Limpia lo que se haya impreso antes, para no acumular resultados
        iniciar_sesion(txt_login_usuario.value, txt_login_clave.value) # Llama al login con lo que el usuario escribió

btn_login.on_click(on_login_click) # Conecta el botón con la función de arriba

# Se imprime el formulario de registro con sus campos de ingreso
print("=== Formulario de Inicio de Sesión ===")
display(txt_login_usuario, txt_login_clave, btn_login, salida_login)

# Registro Manual para probar comportamiento del login respecto al hash almacenado al obtener la misma clave y/o cambiar solo un caracter
registrar_usuario("yoann", "MiClave123")
print()
iniciar_sesion("yoann", "MiClave123")   # hashes deberían coincidir, Login deberia ser exitoso
print()
iniciar_sesion("yoann", "miclave123")   # solo cambia una letra, el hash debe ser totalmente distinto por lo tanto el login debe ser incorrecto

"""Como funciona el sistema de login:

1.  El usuario escribe su usuario y contraseña en el formulario.
2.  El sistema busca ese usuario en usuarios_db y saca la sal que se guardó en el registro (la sal no es secreta, se puede guardar en texto plano).
Con esa misma sal + la contraseña que el usuario acaba de escribir, se calcula un hash nuevo, desde cero — exactamente el mismo cálculo que se hizo en el registro.
3. Se comparan dos hashes: el que ya estaba guardado en la base de datos, contra el que se acaba de calcular. Si son idénticos, la contraseña es correcta (porque solo esa contraseña, combinada con esa sal, puede producir ese hash exacto). Si no coinciden, es incorrecta.

1. Nunca se guarda la contraseña real — solo sal y hash. Si alguien roba usuarios_db, no tiene las contraseñas.
2. La sal es un valor aleatorio distinto por usuario. Sin ella, dos usuarios con la misma contraseña ("123456", por ejemplo) tendrían el mismo hash
3. El login no "descifra" nada, simplemente repite el mismo cálculo con la contraseña ingresada y compara el resultado.
"""