# -*- coding: utf-8 -*-
"""Firma Digital en Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2gmc-MIJx-zw0nMyBYOlhRT-E2dPygw

Objetivo: Comprender cómo se genera y verifica una firma digital.
Pasos:
1. Instala cryptography en Python.
2. Genera un par de claves (privada y pública) usando RSA.
3. Firma un mensaje usando la clave privada.
4. Verifica la firma del mensaje con la clave pública.
5. Modifica el mensaje y verifica que la firma falle.
Reto: Explica brevemente en tus apuntes cómo se garantiza autenticidad y no repudio
usando firma digital.
"""

# === COMPLETA LOS DATOS DEL GRUPO ===

# Integrante 1
nombre_1 = "Yoann Esteban Jacome Garcia"
codigo_1 = "1202597"

# Integrante 2
nombre_2 = "David Santiago Crispoca Taborda"
codigo_2 = "1202557"

# Integrante 3 (si aplica)
nombre_3 = "María Alejandra Suarez Cuesta"
codigo_3 = "1202604"

integrantes = [(nombre_1, codigo_1), (nombre_2, codigo_2)]
if nombre_3:
    integrantes.append((nombre_3, codigo_3))

print("Grupo de trabajo:")
for i, (n, c) in enumerate(integrantes, 1):
    print(f"  {i}. {n} — {c}")

# Importación de librerías: rsa y padding para generar llaves y firmar, hashes para el algoritmo SHA-256 usado internamente
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes

# Función para generar el par de llaves RSA (privada y pública), no recibe parámetros
def generar_llaves():
      # Se genera la llave privada con un exponente público estándar y un tamaño de 2048 bits (seguro actualmente)
    llave_privada = rsa.generate_private_key(
        public_exponent=65537,  # valor estándar recomendado
        key_size=2048            # tamaño de llave seguro actualmente
    )
     # La llave pública se deriva matemáticamente de la privada, no se genera por separado
    llave_publica = llave_privada.public_key()
    return llave_privada, llave_publica


# Función para firmar un mensaje, tomando como parámetros el mensaje y la llave privada, y retorna la firma en bytes
def firmar_mensaje(mensaje: str, llave_privada) -> bytes:
    mensaje_bytes = mensaje.encode('utf-8') # se convierte el mensaje a bytes antes de firmar
    # .sign() firma el mensaje, primero calcula su hash SHA-256, y ese hash es lo que realmente se firma con la llave privada
    firma = llave_privada.sign(
        mensaje_bytes,
        padding.PSS(  # esquema de padding recomendado para firmas RSA
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()  # primero se calcula el hash del mensaje, y eso es lo que se firma
    )
    return firma


# Función para verificar una firma, tomando como parámetros el mensaje, la firma y la llave pública, retornando un bool que determina si la firma es valida o no
def verificar_firma(mensaje: str, firma: bytes, llave_publica) -> bool:
    mensaje_bytes = mensaje.encode('utf-8')
    # .verify() no devuelve True/False directamente: si la firma es válida no hace nada, si es inválida hace una excepción, por lo tanto
    # se aplica el concepto del try y el except explicado en clase para intentar la verificación y, si lanza una excepción, capturarla y convertirla en False
    try:
        llave_publica.verify(
            firma,
            mensaje_bytes,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        return True  # si no hubo excepción, la firma es válida
    except Exception:
        return False  # se atrapa la excepción y se retorna False en su lugar

# Prueba:
# Se generan las llaves privada y pública
llave_privada, llave_publica = generar_llaves()

# Se firma el mensaje original con la llave privada
mensaje_original = "Este documento fue firmado por Alice"
# Se hace llamado a la funcion firmar mensaje, y se mandan los parametros: el mensaje original y la llave privada. Con esto se genera la firma y se almacena en una variable
firma = firmar_mensaje(mensaje_original, llave_privada)
print(f"Mensaje original: {mensaje_original}") # Se muestra el mensaje original
print(f"Firma (hex): {firma.hex()[:64]}...")  # Se muestra recortada porque es una cadena muy larga

# Llamado a funcion verificar_ firma para verificar la firma con la llave pública, sobre el mensaje sin alterar
es_valida = verificar_firma(mensaje_original, firma, llave_publica)
print(f"\n¿Firma válida sobre el mensaje original?: {es_valida}")  # Deberia ser True

# Se modifica el mensaje y se verifica la misma firma contra el mensaje alterado
mensaje_alterado = "Este documento fue firmado por Bob"
es_valida_alterado = verificar_firma(mensaje_alterado, firma, llave_publica)
print(f"¿Firma válida sobre el mensaje alterado?: {es_valida_alterado}")  # Deberia ser False